version: '3.8'
services:
  app:
    image: movierating6
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/movie_rating?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root

    depends_on:
      - db

  db:
    image: mysql:8.0.27
    restart: always
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie_rating
      MYSQL_USER: admin
      MYSQl_PASSWORD: root


